spring.application.name=backend

spring.datasource.url=jdbc:h2:mem:beacon
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
jwt.secret=this-is-my-secret-key-which-is-at-least-32-characters